# Lable Encoder

### sklearn.preprocessing.LabelEncoder
##### class sklearn.preprocessing.LabelEncoder
##### fit -> transform

In [2]:
#Lable인코딩 
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

#객체생성 후 ->fit(), tranform()으로 label 인코딩
encoder = LabelEncoder()
encoder.fit(items)
lables = encoder.transform(items)
print('인코딩 변환값:', lables)  #인코딩과정


인코딩 변환값: [0 1 4 5 3 3 2 2]


In [3]:
#인코딩 = 코드화, 암호화
#인코딩은 사람이 인지할 수 있는 형태의 데이터를 약속된 규칙에 의해 컴퓨터가 사용하는  0과 1로 변환하는 과정

#디코딩 = 역코드화, 복호화
#인토딩의 반대로 사람이 이해할 수 있도록 바뀌주는 것 => byte형식을 문자열(str)로 변환

print('인코딩 클래스:', encoder.classes_) #디코딩과정


인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [5]:
print('디코딩 원본 값:', encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3]))

디코딩 원본 값: ['전자렌지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


# One Hot encoding

### sklearn.preprocessing.OneHotEncoder
##### class sklearn.preprocessing.OneHotEncoder(*, categories='auto', drop=None, sparse=True, dtype=<class 'numpy.float64'>, handle_unknown='error')

In [6]:
#원-핫 인코딩 - 속도는 느리지만 예측의 결과가 좋음

from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

encoder = LabelEncoder() 
encoder.fit(items)
labels = encoder.transform(items)

labels = labels.reshape(-1,1) #레이블 인코딩->원핫 인코딩하면 reshape 배열의 차원 재구조화
# reshape()에서 -1의 의미: https://rfriend.tistory.com/345
# 
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [ ]:
#standardscaler
#fit을 할때마다  값이 조금씩 차이남..?
#주의할 내용으로 학습 데이터 세트와 테스트 세트에 fit()과 transform()을 적용할 때 주의가 필요합니다. Scaler객체를 이용해 학습 데이터 세트로 fit()과 transform()을 적용하면 테스트 데이터 세트로 다시 fit()을 수행하지 않고 학습 데이터 세트로 fit()을 수행한 결과를 이용해 transform() 변환을 적용해야 한다는 것입니다. 

#즉, 학습 데이터로 fit()이 적용된 스케일링 기준 정보를 그대로 테스트 데이터에 적용해야 하며, 그렇지 않고 테스트 데이터로 다시 새로운 스케일링 기준 정보를 만들게 되면 학습 데이터와 테스트 데이터의 스케일링 기준 정보가 서로 달라지기 때문에 올바른 예측 결과를 도출하지 못할 수 있습니다. 
#머신러닝 모델은 학습 데이터를 기반으로 학습되기 때문에 반드시 테스트 데이터는 학습 데이터의 스케일링 기준에 따라야 합니다. 따라서 테스트 데이터에 다시 fit()을 적용해서는 안 되며 학습 데이터로 이미 fit()이 적용된 Scaler객체를 이용해 transform()으로 변환해야 합니다. 
#https://nicola-ml.tistory.com/86